# .nosana-ci.yml
nosana:
    description: Hacker House Demo

global:
    image: registry.hub.docker.com/library/node:18

    trigger:
        branch:
            - main

    environment:
      PINATA_JWT_KEY:
        type: nosana/secret
        endpoint: https://secrets.k8s.prd.nos.ci
        value: PINATA_JWT_KEY

jobs:

    - name: Install and Upload to IPFS
      commands:
        - ls
        - export FOO=HackerHouse
        - echo $FOO
