# .nosana-ci.yml
nosana:
    description: Hacker House Demo

global:
    image: registry.hub.docker.com/library/node:18

    trigger:
        branch:
            - main

    environment:
      PINATA_JWT_KEY:
        type: nosana/secret
        endpoint: https://secrets.k8s.prd.nos.ci
        value: PINATA_JWT_KEY

jobs:

    - name: Install and Upload to IPFS
      commands:
        # - npm install
        # - npm run generate:ipfs
        # - npm run ipfs
        - corepack enable
        - corepack prepare pnpm@latest --activate
        - pnpm install
        - pnpm run generate:ipfs
        - pnpm run ipfs  
