# .nosana-ci.yml
nosana:
    description: Hacker House Demo

global:
    image: alpine:latest

    trigger:
        branch:
            - main
jobs:

    - name: Test
      commands:
        - ls -lah
        - env
        - pwd
